### ISSUE TITLE
0.6.1 release to PyPi

### ISSUE THREAD

**Issue by antinescience** [channelcat/sanic#1016]
Hey folks,

There's been a bunch of substantive changes in the past few months; I think it warrants a release of 0.6.1 (or 0.7, considering there may be large changes in PRs like #939). Any chance we could get a new candidate uploaded to PyPi? 

If there's a better place to ask this, I'm happy to head there.

**Comment by seemethere** [comment]
I'll make some time to do a full `0.7.0` release this week

**Comment by seemethere** [comment]
cc @r0fls

**Comment by antinescience** [comment]
Thanks!

**Comment by pikeas** [comment]
Please update the CHANGELOG as well!

**Comment by ashleysommer** [comment]
@pikeas 
I think the changelog has been abandoned at this point. There has been a _lot_ of releases since it was last updated. For now, the best way to see changes is in the Releases page on github, here: https://github.com/channelcat/sanic/releases

@seemethere 
Do you still plan to do a 0.7.0 release soon? Is there anymore testing or QC you need before it is released, given the large number of changes since 0.6.0, including my commits in #939 ?

For what its worth, I am using Sanic@master in a semi-production application at work and it's performing great.

**Comment by aalhour** [comment]
Any updates on the v0.7 release @seemethere?

**Comment by marijngiesen** [comment]
If you're too busy at the moment @seemethere, isn't there someone else who can release 0.7.0?

**Comment by seemethere** [comment]
Sorry about the delay guys! Have had a lot on my plate recently but `0.7.0` should be uploading to pypi as I write this!
