### ISSUE TITLE
order of response middleware

### ISSUE THREAD

**Issue by imnisen** [channelcat/sanic#1046]
Hi,
when I read the [doc](http://sanic.readthedocs.io/en/latest/sanic/middleware.html#modifying-the-request-or-response) , it says the response middleware will apply in order (as defined). However, when I make some test, it shows the order is reversed. so I check the code as below:
```
def register_middleware(self, middleware, attach_to='request'):
        if attach_to == 'request':
            self.request_middleware.append(middleware)
        if attach_to == 'response':
            self.response_middleware.appendleft(middleware)
        return middleware
```
so when add  a response it add to left side, so when handle a response, 
```
 async def _run_response_middleware(self, request, response):
        if self.response_middleware:
            for middleware in self.response_middleware:
                _response = middleware(request, response)
                if isawaitable(_response):
                    _response = await _response
                if _response:
                    response = _response
                    break
        return response
```
the latter middleware will apply first!!
Am I misunderstand some?

Appreciated!

**Comment by ashleysommer** [comment]
You are correct. The documentation is inaccurate.
_Request Middleware_ is applied in the order it is added, but
_Response Middleware_ is applied in the _reverse_ order than it was added.

In this case, the last middleware defined/added will be executed first.

This is because middleware is executed in _priority_ order. With the first middleware having the highest priority. In terms of request middleware, the highest priority is the middleware that gets the opportunity to respond to the request _first_. And with response middleware, the highest priority is the middleware that gets the opportunity to modify the response _last_.

**Comment by imnisen** [comment]
The priority makes sense! Thanks!
