### ISSUE TITLE
Why should we check `if isawaitable(response):`  in app.py/handle_request?How about removing them to make sanic faster?

### ISSUE THREAD

**Issue by caitinggui** [channelcat/sanic#1086]

**Comment by ashleysommer** [comment]
It is because sanic can use both synchronous (normal) and asynchronous (async, coroutine) python functions as its request handlers.

At runtime, the sanic app doesn't know if the response was handled by a normal function or an async function.

If it was a normal function, the `response` variable will contain the actual response, and we can simply return it, however if the response hander was an async function, the `response` variable we get back will actually be a Future representing a value that will resolve sometime in the future.

The easiest/fastest way to check if the `response` is a real response or a Future response, is to use `if isawaitable()`. If it _is_ awaitable, we have to use `await` to wait for the Future to resolve to get its response, before we can return it.

I hope that helps to clear up your question.

**Comment by caitinggui** [comment]
@ashleysommer thanks very much
