### ISSUE TITLE
Failure to write request swallows problem

### ISSUE THREAD

**Issue by jasonab** [channelcat/sanic#115]
server.py, line 137-139:
If the response is malformed, Sanic will log an error (thankfully), but will not return any kind of response (simply killing the connection).

Sanic should generate an exception that can be handled by the error handler, and ultimately return a 500.

Note that this can be generated by attempting to return a Flask-type tuple instead of a Sanic response object.

**Comment by r0fls** [comment]
@seemethere the natural thing to do here in my opinion is to import the exceptions and raise one if the response from the server is invalid. However that would cause a circular import because exceptions uses response.py. Should we refactor, and include exceptions in response.py? That's tye typical way to deal with circular imports, since if they both rely on each other there is no reason to keep them separate. 

Or, can you think of another way of doing this?

**Comment by jasonab** [comment]
Method write_response:
 except Exception as e:
            self.bail_out(
"Writing response failed, connection closed {}".format(e))

**Comment by seemethere** [comment]
Closed with #223
