### ISSUE TITLE
Question - asynchronous work with progress indicator not behaving properly with more than 1 worker.

### ISSUE THREAD

**Issue by UNIcodeX** [channelcat/sanic#1152]
I've put together a small web app to trigger some work, and be able to poll the results of that work. This is an attempt to explore the possibility of using asyncio, rather than celery, to perform some work and be able to interact with its progress.

If the workers are set to more than 1, then the status does not display, and I think this has to do with the session, but wanted to ask the Sanic devs directly for input on how to make this work as intended with multiple workers.

The gist for it is in the link below:
https://gist.github.com/UNIcodeX/f1ee8579719fbef6edaad71c96cd0fe2

Thank you in advance for your time.

**Comment by xen** [comment]
Don't use session object. It works a different way that you expect. During process function, you are changing the item that doesn't save its state. Since it happens only when `save_session` executed. It is like changing the variable of the object taken from the database inside of the loop without calling save function.

Take a look at the [redis](https://github.com/aio-libs/aioredis) database. And use `set` and `get` methods for the desired variable. Then it will be accessible between calls.

**Comment by UNIcodeX** [comment]
@xen Awesome! I'll definitely give that a try. thanks!

**Comment by xen** [comment]
@UNIcodeX you are welcome. I think this issue can be closed.
