### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by marijngiesen** [channelcat/sanic#1170]
The last release was from December. Isn't it time for a new one? There have been a lot of positive changes/improvements to the codebase.

**Comment by ashleysommer** [comment]
I agree it is time for a new release.
Though we should probably wait to see if https://github.com/channelcat/sanic/pull/1179 gets pulled it.
It will potentially break code for people using streaming responses, so it is good to get in a release as soon as possible (while we are still doing early beta releases).

**Comment by hassanalinali** [comment]
I'm also waiting since February to use those shiny new upcoming nested blueprints

**Comment by GoodiesHQ** [comment]
Nested blueprints have been in the development branch for months now. Is there any ETA on 0.7.1?

**Comment by marijngiesen** [comment]
Any ETA yet?

**Comment by DirkGuijt** [comment]
@r0fls what is the hold up?

**Comment by vltr** [comment]
I'm interested on that, too. There were a few promises on #1134 but no return ... To be honest, that's kind of frustrating :sweat_smile:

I'm looking forward to see #1244, #1220, #1179 and #1127 merged as well. If that's a hands-on / time issue, I'm prompt to help :+1:

**Comment by ashleysommer** [comment]
@DirkGuijt I'm not a project collaborator, I don't get to decide when a new release goes out. I just write PRs and hope they get merged.

@vltr I feel your frustration.

One thing you can do to help if youre keen is manually patch a deployment of Sanic with each of those PRs you mentioned, and do some testing to ensure everything works properly for you. Then in the comment thread for each of those PRs, make a comment saying you've manually tested the PR and it does what it says it does, doesn't break anything (or does) and that you'd like to see it merged.

This project is powered by community, and relies on the participation of the community to get things done.

**Comment by vltr** [comment]
Thanks for your clarification, @ashleysommer !

In fact, [I did test](https://github.com/channelcat/sanic/pull/1244) some of the proposed PRs in the last couple of days, leaving my feedback in there also.

So, just to understand better (on how can I help the project, knowing that it is community driven), all these PRs are not merged / approved into the project due to the lack of testing? If so, how can we (the community) be able to help, provide feedback and get them merged (or not)? I know you're just a collaborator (your answer above is not the first one I've seen you saying that), so perhaps @r0fls can help us to help the project? I am a little lost here on "how to help the project" ...

My best regards,
Richard.

**Comment by r0fls** [comment]
I'm going to close this issue since there is a fresh version here with ongoing conversation: https://github.com/channelcat/sanic/issues/1245
