### ISSUE TITLE
response_timeout leaks memory

### ISSUE THREAD

**Issue by abuckenheimer** [channelcat/sanic#1273]
Hey Folks,

Found an interesting case the other day where my server was running out of memory because handlers cancelled from a response_timeout would keep references to their local context. This may be an asyncio  misunderstanding on my part but I found this quite surprising, here's a test to illustrate (sorry if its a bit verbose):

```
import asyncio
import weakref
from sanic import Sanic, response


class LeakedObject:
    pass


leaked = weakref.WeakSet()
app = Sanic(__name__)


@app.route("/slow")
async def slow_handler(request):
    l = LeakedObject()
    leaked.add(l)
    await asyncio.sleep(2)
    return response.text('OK')


@app.route("/fast")
async def fast_handler(request):
    l = LeakedObject()
    leaked.add(l)
    return response.text('OK')

app.config.RESPONSE_TIMEOUT = 1


# this works
def test_completed_request_cleaned_up():
    results = [None, None]

    @app.listener('after_server_start')
    async def _collect_response(sanic, loop):
        results[0] = await app.test_client._local_request('get', '/fast')
        # at this point the request is done leaked should no longer have a
        # weakref to LeakedObject
        results[1] = list(leaked)
        app.stop()

    app.run(host='127.0.0.1', debug=True, port=app.test_client.port)
    resp, references_leaked = results
    assert resp.status == 200
    assert resp.body == b'OK'
    assert references_leaked == []
    app.listeners['after_server_start'].pop()


# this does not
def test_timed_out_request_cleaned_up():
    results = [None, None]

    @app.listener('after_server_start')
    async def _collect_response(sanic, loop):
        results[0] = await app.test_client._local_request('get', '/slow')
        # at this point the request is done leaked should no longer have a
        # weakref to LeakedObject
        results[1] = list(leaked)
        app.stop()

    app.run(host='127.0.0.1', debug=True, port=app.test_client.port)
    resp, references_leaked = results
    assert resp.status == 503
    assert resp.body == b'Error: Response Timeout'
    assert references_leaked == []  # <<< fails here
    app.listeners['after_server_start'].pop()


if __name__ == '__main__':
    test_completed_request_cleaned_up()
    test_timed_out_request_cleaned_up()
```

**Comment by abuckenheimer** [comment]
@ashleysommer I think you'd be the expert here, side note I can't quite figure out how to use  `ReuseableSanicTestClient` here but it could potentially reduce the testing boilerplate above

**Comment by abuckenheimer** [comment]
so I've found an issue with response_timeout_callback (just not my issue), namely when it tries to cancel the _request_handler_task the CancelledError gets caught in handle_request's try/catch which leads it to continue chugging along even though the transport is already closed by .write_error(). I think that gets solved  with this https://github.com/channelcat/sanic/compare/master...abuckenheimer:fix_response_timeout-1273 but that doesn't fix my first issue.

**Comment by ashleysommer** [comment]
@abuckenheimer 
This is a really interesting problem. Thank you for bringing it up.

The ReuseableSanicTestClient probably wouldn't help in this case, you're right it is very hard and counter-intuitive to use, it was made for one very specific test case. Your boilerplate code in your test is fine for testing this behavior.

I will look into fixing that _request_handler_task canceled issue you pointed out, and I'll dig a bit deeper into the memory leak you've described.

**Comment by ashleysommer** [comment]
@abuckenheimer 
I've gone down a very interesting rabbit hole with this one (specifically, the memory leak you were seeing)
Some findings:
1) I could only reproduce it with asyncio running in Debug mode. Eg.
`app.run(host='127.0.0.1', debug=True, port=app.test_client.port)`
If I turned off debugging with `debug=False`, the test was passing.
2) I removed uvloop to run sanic using the native CPython asyncio implementation. This allowed slightly easier debugging of the problem, but the results of the memory leak test were identical.
3) With debug mode on, even after modifying sanic heavily to ensure the response object and its context is destroyed, the context was still leaked.
4) I read some interesting articles and stackoverflow answers about using the `sys` module to test for reference count of an object (`sys.getrefcount(x)`). And also down the track, using the `gc` module to determine all referrers of a particular object (`gc.get_referrers(x)`).
5) After the modifications to sanic to ensure the response and context was destroyed, there was still 1 reference to the LeakedObject, and the reference was inside something called a `frame object`.
6) I believe this is caused by running asyncio (and uvloop) in debug mode, the library keeps a copy of the Task stack frame in memory, with a hard reference to all context variables, for debugging  purposes.
7) I found out that you should always call `gc.cleanup()` before calling `gc.get_referrers()` to force the garbage collector to run, to avoid giving false results.
8) After running `gc.cleanup()` the reported problem disappears. Doing that seems to force the final 
referrer to let go of the object, and the object gets de-allocated.

This passes:
```
import gc
def test_timed_out_request_cleaned_up():
    results = [None, None]

    @app.listener('after_server_start')
    async def _collect_response(sanic, loop):
        results[0] = await app.test_client._local_request('get', '/slow')
        # at this point the request is done. `leaked` should no longer have a
        # weakref to LeakedObject
        await asyncio.sleep(1)
        gc.collect()  # <<< only change
        results[1] = list(leaked)
        app.stop()

    app.run(host='127.0.0.1', debug=True, port=app.test_client.port)
    resp, references_leaked = results
    assert resp.status == 503
    assert resp.body == b'Error: Response Timeout'
    assert references_leaked == []  # <<< no longer fails here
    app.listeners['after_server_start'].pop()
```

**Comment by abuckenheimer** [comment]
good catch, my whole issue may come down to debug mode. What I find strange though is that I only found this bug because the memory leaks lasted for a long time which makes it seem like the garbage collector should have had plenty of time to do its thing. I did find this issue on windows though so there may be something else weird going on, will have to check in on it.

**Comment by abuckenheimer** [comment]
following up I didn't realize that gc only collects after a set number of object allocations so by having a handful of very large objects the threshold must not have been passed. Will consider this closed, thanks for your help @ashleysommer

**Comment by ArminMaz** [comment]
This issue saved me big times.
Thank you so much @abuckenheimer
