### ISSUE TITLE
Debug breakpoints in PyCharm stops working after upgrading to 0.8 or later

### ISSUE THREAD

**Issue by lakaf** [channelcat/sanic#1313]
Hi there,

I am developing sanic application using JetBrains PyCharm (version 2018.2.3).
The breakpoint debugging function there was working fine on sanic 0.7.0, but after I upgraded to 0.8 or later all the breakpoints can never get hit any more.

**Comment by isogram** [comment]
hi @lakaf any solution for this case?

**Comment by vltr** [comment]
A discussion regarding `auto_reload` support and better IDE integration is ongoing in the [community forums](https://community.sanicframework.org/t/following-auto-reload-support-for-windows/35). The title refers to Windows, but everything is being overhauled to work seamlessly on the three major platforms (Linux, Windows and mac OS).

**Comment by lakaf** [comment]
> hi @lakaf any solution for this case?

Yeah as vltr mentioned this is related to `auto_reload`, you could set `auto_reload` to `False` in sanic's run call and this will fix this issue for now.

**Comment by isogram** [comment]
thanks @lakaf 👍

**Comment by emdotem** [comment]
Still open, can we fix it?

**Comment by Tronic** [comment]
Currently the main process runs auto_reload and child processes do everything else, if auto reloader is enabled. I suppose this would require refactoring so that the main process does serving and the reloader is a child. This should be fine on POSIX platforms but I wonder if that can work on Windows, i.e. whether killing the main process would there kill all the children incl. the reloader (not sure how if Windows automatically kills child processes when the parent is killed; POSIX does not).

**Comment by charlesXu86** [comment]
Just do it as follows: Edit configrations -> Parameters : --debug=True

**Comment by charlesXu86** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/13271848/94993421-797e1600-05c3-11eb-8f1a-1606ce984167.png">
this is working
