### ISSUE TITLE
NoneType object has no attribute 'should_keep_alive'

### ISSUE THREAD

**Issue by bforchhammer** [channelcat/sanic#181]
Hi,

I have setup a small sanic server locally and I get the following error message from time to time... 

    2016-12-03 11:44:04 - Writing response failed, connection closed 'NoneType' object has no attribute 'should_keep_alive'

I could be wrong, but I does not appear to be related to any of my requests... it just happens from time to time. Any idea why this happens?

**Comment by 38elements** [comment]
I think that if [Request Timeout](https://github.com/channelcat/sanic/blob/89e2084489a8db6ba3e1fd69ebbcd5d15d0adf42/sanic/server.py#L86) occurs between [connection_made](https://github.com/channelcat/sanic/blob/89e2084489a8db6ba3e1fd69ebbcd5d15d0adf42/sanic/server.py#L62) and [data_received](https://github.com/channelcat/sanic/blob/89e2084489a8db6ba3e1fd69ebbcd5d15d0adf42/sanic/server.py#L92), that error will occur, Because [self.parser](https://github.com/channelcat/sanic/blob/89e2084489a8db6ba3e1fd69ebbcd5d15d0adf42/sanic/server.py#L105) is not  generated.

**Comment by seemethere** [comment]
Closed with #183
