### ISSUE TITLE
Router issue when two route share nearly similar paths

### ISSUE THREAD

**Issue by njordr** [channelcat/sanic#395]
Hi.

I created two routes:
/binders/<smartcabinet_id:string>/<binder_id:string>
/binders/<binder_id:string>/samples

It seems that the second one will be never used, so I need to change the path, also if the REST definition is right because, in my use case, samples belongs to binders.

Any advice?

sanic 0.2.0

**Comment by argaen** [comment]
I don't know how the router is implemented but in other frameworks, the order of definition of the routes matters.

Try adding the route with the `samples` first and the other with the regular expression after.

I.e:

```python
app.add_route(handler1, '/binders/<binder_id:string>/samples')
app.add_route(handler2, '/binders/<smartcabinet_id:string>/<binder_id:string>')
```

**Comment by seemethere** [comment]
Yeah the way the router works with dynamic routes is through regex so if you define `/binders/<smartcabinet_id:string>/<binder_id:string>` first then it'll pretty much override any other routes that would match the same regex.

So even though you named different params for the routes they'll still get counted as the same route since dynamic routes work through regex. Unfortunate side effect of dynamic routes in the first place since there's no real easy way to determine if a route matches without regex.

What I would suggest in this scenario is that you either define it first as @argaen said or handle special cases where the `binder_id` is equal to `samples`.

**Comment by njordr** [comment]
ok, thanks
