### ISSUE TITLE
periodic tasks/ cron 

### ISSUE THREAD

**Issue by itielshwartz** [channelcat/sanic#437]
Hi,

I'm writing my first sanic server,  I have some async function:
```
async def async_task():
    return await asyncio.sleep(1)

```
Is there any code to run it using the app loop?
Is there some build in cron mechanism to run this every X seconds?

thanks

**Comment by r0fls** [comment]
You can use the `add_task` method:

```
async def async_task():
    return await asyncio.sleep(1)

app = Sanic()
app.add_task(async_task)
app.run()
```

This ensures your task is started before the server. There is nothing like cron though. You could simply use a `while True:` statement or look into https://github.com/dbader/schedule

**Comment by seemethere** [comment]
You could also use a `loop.call_later` specify a time between calls and then just keep re-upping it in the same function.

**Comment by itielshwartz** [comment]
Thanks for the quick help!
few questions:
1. does add_task block the app from starting?
2. i can't seem it in the current sanic version (pip) , do you recommend using the github version? 
3. how can i get the app loop?

**Comment by r0fls** [comment]
> 1. does add_task block the app from starting?
No
> 2. i can't seem it in the current sanic version (pip) , do you recommend using the github version?
Yes, if you need the latest features before they're updated there.
> 3. how can i get the app loop?
The `app.loop` property calls `asyncio.get_event_loop()`. Use that, but don't start running it before you call `app.run()`. So, you can use the loop in your routes if you like with `app.loop` or `asyncio.get_event_loop()`, but be a bit careful because sanic creates a new loop in `app.run` so if you've already started a different one running, that will fail.

**Comment by itielshwartz** [comment]
sounds great, thanks.
