### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by yunstanford** [channelcat/sanic#781]
Test coverage is pretty low now. Increasing test coverage will help to catch issues fast.

**Comment by seemethere** [comment]
What do you think we're missing in our test coverage?

Are there any big functional gaps?

**Comment by yunstanford** [comment]
i didn't look deeply though, but the code coverage is pretty low. but i can take a look.

**Comment by r0fls** [comment]
I think there may be an issue with how it's reporting. Last I remember @miguelgrinberg found something here: https://github.com/channelcat/sanic/pull/469#issuecomment-281204792

However it's only showing 17% coverage so it may still be messed up.

**Comment by miguelgrinberg** [comment]
Yeah, coverage was off during the unit tests, if I remember correctly. I did a coverage run by hand at the time and got something like 85%.

**Comment by asvetlov** [comment]
85% roughly means nothing: the test suite covers normal execution paths and never touch on very problematic cases like error handling etc.
Values less than 95% are almost useless. You should rely on users feedback only.

**Comment by seemethere** [comment]
Yeah I think the automated tools for code coverage provide a clear enough picture.

I'm fine with how were doing testing for now, albeit it could have better metrics.

Closing this for now but we could revisit the idea of having better metrics or perhaps finding a code coverage tool that covers our use cases.

**Comment by asvetlov** [comment]
What better coverage tool are you talking about?
You just need run test suite with coverage.py enabled and publish results on any OSS friendly tool like codecov.io
After that you should work hard on coverage improvement by every PR and covering dark corners in existing code base.
It's obvious, isn't it?

But if you reject the purpose at all -- it's up to you.

**Comment by miguelgrinberg** [comment]
I think I disagree with the statement that "85% coverage is almost useless", for the same reason. When you are in the 80s you have pretty good coverage of the "normal" use cases. To me, that means that what most people do everyday is going to be covered.

I agree that covering the error handling and other not commonly used parts of the code is a great goal, but you have to start from something, and really, 85% is more than most projects you come across.

I would humbly suggest you guys should enable coverage during unit tests, at least so that people see more accurate numbers in the build results. The tox configuration has this:

    pytest tests {posargs}
    coverage erase
    coverage run -m sanic.app
    coverage report

Note how the pytest run is not under coverage. This should be a simple fix to make. Happy to add a PR if you guys like.

**Comment by seemethere** [comment]
@asvetlov 

I mean with `pytest-cov` pytest plugin we have about 79% coverage. If it's about changing the tool that's fine with me. I'll leave this open as a tracker until we get the `pytest-cov` plugin into our normal running jobs. I'll also add a make target so you can run it in the docker container as well.

**Comment by messense** [comment]
Integrate with `codecov.io` would be awesome.

**Comment by yunstanford** [comment]
i can push a commit to integrate that with `coveralls.io` or `codecov.io`, but probably it's better to ask owner to do that. it needs enable the access to this repo.

**Comment by seemethere** [comment]
`pytest-cov` was added in #789

**Comment by seemethere** [comment]
Code coverage integration with a service would be nice but it'd be dependent on @channelcat since I don't have admin access.

Going to close this until we get a response from @channelcat
