### ISSUE TITLE
Worker dont pick connections after restart

### ISSUE THREAD

**Issue by lvalladares** [channelcat/sanic#912]
Im running a test sanic implementation with gunicorn following the instructions in the docs, i settedthe max request jitter in gunicorn to 200 (just for test) and do a `wrk -c 200 -d 20s -t 10` but im only getting 200 RPS.

I checked the console and after the restart (when the ASCII art of sanic appears again) dont appear any connections, it seems like the workes arent pickin up connections again.

I tried setting max requests jitter to 0 and the RPS goes to 4k.

I dont know if this is a expected behaviour or a bug

**Comment by yunstanford** [comment]
1. restart means shutdown the worker process gracefully and fork the master process again. Those connections should been closed due to the shutdown, so should not pick up i think. I don't know how `wrk` works internally, it may need to establish new connections.

2. `max_requests` and `jitter` are two different things.

**Comment by lvalladares** [comment]
Gunicorn has an option called max_requests_jitter (http://docs.gunicorn.org/en/latest/settings.html#max-requests-jitter). I undertand this setting basically "randomize" the max_request parameter inside a range

i do some research and this is related to wrk, because with apache bench works great, so im clossing this.
