### ISSUE TITLE
Discussion - Sanic vs Go?

### ISSUE THREAD

**Issue by davidtgq** [channelcat/sanic#987]
From the benchmarks, it looks like the only real competition is Go. I've looked at the pros/cons of each but would also like to get the insight of people who have used both recently. The reason I ask here is because the Sanic devs almost certainly knew about Go before making Sanic, so I guess there's something lacking with Go that spawned the development of uvloop/Sanic.

That said, here are some questions I have in mind so far to start the discussion:

 - Which is more intuitive to think/work in?
 - Which performs better in production, i.e. fewer Achilles heels?
 - Which has better ecosystem and community involvement/forums etc?

I've read some blogs about companies switching from Python to Go, but they only talk about PyPy etc, nothing about uvloop or any of the newer async stuff, so I'm taking their anecdotes with grains of salt... They also talk about limitations with the Python GIL, are Sanic/uvloop still constrained by this?

**Comment by Yougigun** [comment]
wondering

**Comment by ahopkins** [comment]
With all due respect to @davidtgq, I am not sure the questions posed here are too relevant since it is asking about a comparison between a web server/framework and a programming language. Both are trying to achieve very different things.

The conversation would be more relevant about the pros and cons working in one language versus the other, which is sort of outside the scope of what the Sanic team is working on. At the end of the day, it is sort of fallacious to think that there is **a single best solution** to anything. While a conversation could be had about why one would or would not choose Sanic over Django or Flask (being the most popular Python frameworks), I am not even sure where one would start a conversation comparing Sanic to Go.

**Comment by aclimdler** [comment]
https://yogesh-sharma.medium.com/python-sanic-vs-golang-mux-d9fc2e5eb723
