### ISSUE TITLE
`request.files` is empty on HTTP POST request w/ files.

### ISSUE THREAD

**Issue by iwasaki-kenta** [channelcat/sanic#995]
Hello,

I tried the examples available for accepting HTTP requests containing files. `request.files` yields an empty dictionary with the code below:

```python
@app.route('/test', methods=['OPTIONS', 'GET', 'POST'])
async def post_json(request):
    test_file = request.files.get('test')

    print(test_file)

    file_parameters = {
        'body': test_file.body,
        'name': test_file.name,
        'type': test_file.type,
    }

    return response.json(
        {"received": True, "file_names": request.files.keys(), "test_file_parameters": file_parameters})
```

Using a `Content-Type` of `multipart/form-data` yields an error:

```
2017-10-28 08:02:41 - (sanic)[ERROR]: Failed when parsing form
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/request.py", line 113, in form
    boundary = parameters['boundary'].encode('utf-8')
KeyError: 'boundary'
```

Using a `Content-Type` of `application/x-www-form-urlencoded` yields:

```
2017-10-28 08:01:58 - (sanic)[ERROR]: Failed when parsing form
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/request.py", line 110, in form
    parse_qs(self.body.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 166: invalid start byte
```

I'm using Postman as my HTTP Client.

![image](https://user-images.githubusercontent.com/8392982/32128260-4fe1a752-bbb7-11e7-9194-d2ba47d0bab5.png)

**Comment by bwangel23** [comment]
Hello, I think your `request.files.get("filename")` statement gets a empty dict because you did not set your `Content-Type` to `multipart/form-data`.

At the same time, I think you shoud install the sanic from master(`pip install --upgrade git+https://github.com/channelcat/sanic.git@master`) and re-run your program.

I write a upload-file program with the lastest sanic(install from master branch), it worked.

```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-"


from sanic import Sanic
from sanic import response

app = Sanic(__name__)


@app.route("/file", methods=['OPTIONS', 'GET', 'POST'])
async def index(request):
    avatar = request.files.get("avatar")
    file_parameters = {
        "name": avatar.name,
        "type": avatar.type,
    }

    # with open("./avatar.jpg", "wb") as fd:
    #     fd.write(avatar.body)

    return response.json({
        "received": True,
        "file_name": request.files.keys(),
        "test_file_parameters": file_parameters,
    })


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=9000)
```

![](https://imgs.bwangel.me/2017-10-29-092427.png)

At last, there is a error in your program, the `request.file.get("test").body` is the binary data of your file, it's type is `bytes`, cannot be dumped by json, so you cannot write it into the json response.

**Comment by iwasaki-kenta** [comment]
Worked perfectly; thanks a bunch!

**Comment by vkozubal** [comment]
Hey, I have the same issue here. What was the problem? 
Updated to the Sanic to `0.7.0` version. 
Passing `Content-Type: multipart/form-data`
